name: frame_sdk
description: "The Flutter SDK for the Frame from Brilliant Labs"
version: 0.0.6
homepage: 'https://github.com/OkGoDoIt/frame-sdk-flutter'
documentation: 'https://docs.brilliant.xyz/frame/building-apps-sdk/#flutter'


environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_blue_plus: ^1.32.11
  logging: ^1.2.0
  archive: ^3.5.0
  image: ^4.2.0
  just_audio: ^0.9.37
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: xyz.brilliant.frame_sdk
        pluginClass: FrameSdkPlugin
      ios:
        pluginClass: FrameSdkPlugin
  assets:
    - assets/frameLib.lua